### ISSUE TITLE
Number of images

### ISSUE THREAD

**Issue by liuzhuang13** [twtygqyy/pytorch-SRDenseNet#8]
Does "30,000 images" in the result section include the images generated by data augmentation or not?

It seems if I include 30,000 images in the image folder, the script generate_train_srdensenet will run out of memory... 

Thanks

**Comment by twtygqyy** [comment]
Hi @liuzhuang13, yes it does require huge cpu memory for loading a huge h5 data. Alternately, you are split the file in to smaller files,  randomly choose one and grab a batch of images during training.

**Comment by liuzhuang13** [comment]
Thank you!
